import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `vitest --coverage` (@vitest/coverage-v8, added in W0 § 0.1).
    // Istanbul's HTML reporter emits its own JS assets carrying eslint-disable
    // directives, which surfaced as an "Unused eslint-disable directive" warning.
    // Left unignored, `npm run lint` reports a different result depending on
    // whether anyone had run coverage first — and a gate that moves on its own is
    // not a gate (.kiro/steering/engineering-standards.md).
    "coverage/**",
  ]),
]);

export default eslintConfig;
